##
## Theme settings
##

remote_theme:   "Fortelle/databook-theme"


##
## Site settings
##

title:          "Databook Docs"
description:    "The ocumentation for Databook-theme."
logo:           "assets/databook/img/logo.png" 
copyright:      ""
keywords:       ""

baseurl:        #
language:       "en-US"
npm_cdn:        "https://cdn.jsdelivr.net/npm/"
url:            #

permalink:      "/:title:output_ext"
typography:     "doc"
color_scheme:   "light"
accent_color:   "blue"
search:         "content"


##
## Blog settings
##

blog_style:     "full"

paginate:       10
paginate_path:  "/page:num/"


##
## Default settings
##

defaults:
  -
    scope:
      type: "posts"
    values:
      permalink: "/:categories/:title:output_ext"


##
## Service settings
##

toc:            true
analytics:      false
comments:       false
scrollspy: true


##
## Build settings
##

plugins:
  - "jekyll-paginate"
  - "jekyll-sitemap"
  - "jekyll-avatar"
  - "jekyll-feed"
  - "jekyll-mentions"
  - "jekyll-redirect-from"
  - "jemoji"

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
